### ISSUE TITLE
This version （5.24.0） has been unable to download and needs to be updated.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#139]
MODULE=kcodecs
         VERSION=**5.24.0**
          SOURCE=$MODULE-$VERSION.tar.xz
      SOURCE_URL=$KDE_URL/stable/frameworks/$(module_version kf5)
      SOURCE_VFY=sha256:8c849f6c3411fe6036e2b8ae3449d0f5eab86eb491d6252440ff0b860794ffe2
   MODULE_PREFIX=${KDE4_INSTALL_DIR:-/usr}
        WEB_SITE=https://projects.kde.org/projects/frameworks/kcodecs
         ENTERED=20150205
         UPDATED=20160709
           SHORT="manipulate strings using various encodings"

This version （5.24.0） has been unable to download and needs to be updated.

https://download.kde.org/stable/frameworks/

**Comment by lhw828** [comment]
Almost all kde components can not be downloaded and need to be updated.

**Comment by stumbles** [comment]
Same applies here, work is in progress to bump this.

**Comment by stumbles** [comment]
This has been resolved with a bump.
