### ISSUE TITLE
This version (16.04.3) has been unable to download and needs to be updated.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#140]
MODULE=akonadi-calendar
         VERSION=16.04.3
          SOURCE=$MODULE-$VERSION.tar.xz
      SOURCE_URL=$KDE_URL/stable/applications/$VERSION/src
      SOURCE_VFY=sha256:540610f55a4003e72b59b22309e5cdf722a3989583ce8b6739e42eabc9d4fca1
   MODULE_PREFIX=${KDE4_INSTALL_DIR:-/usr}
        WEB_SITE=http://techbase.kde.org/Getting_Started/Build/KDE4/Troubleshooting
         ENTERED=20151122
         UPDATED=20160713
           SHORT="A PIM layer for KDE 4.x"

This version (16.04.3) has been unable to download and needs to be updated.

https://download.kde.org/stable/applications/

**Comment by lhw828** [comment]
Almost all kde components can not be downloaded and need to be updated.

**Comment by stumbles** [comment]
I am aware and in the process of bumping essentially all of kde. Please be patient.

**Comment by stumbles** [comment]
this has been resolved with a bump, closing
