### ISSUE TITLE
kross:build errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#167]
++ Mark Compile start  : "kross" "5.44.0" "Tue, 29 May 2018 14:33:03 +0000"
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /var/lib/lunar/compilers/gcc
-- Check for working C compiler: /var/lib/lunar/compilers/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 

-- Installing in the same prefix as Qt, adopting their path scheme.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
CMake Error at /usr/lib/qt5/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Script" with
  any of the following names:

    Qt5ScriptConfig.cmake
    qt5script-config.cmake

  Add the installation prefix of "Qt5Script" to CMAKE_PREFIX_PATH or set
  "Qt5Script_DIR" to a directory containing one of the above files.  If
  "Qt5Script" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)

-- Configuring incomplete, errors occurred!
See also "/usr/src/kross-5.44.0/kross-oosb/CMakeFiles/CMakeOutput.log".
++ Mark Compile stop   : "kross" "5.44.0" "Tue, 29 May 2018 14:33:06 +0000"

**Comment by lhw828** [comment]
Qt5 seems to be a bit of a problem. @Florin65

**Comment by lhw828** [comment]
@stumbles We expect you to come back soon to maintain Plasma and any others.

**Comment by stumbles** [comment]
I will.
