### ISSUE TITLE
Qt5:Some errors still

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#207]
`g++ -pipe -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -dM -E -o .moc/moc_predefs.h /usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/features/data/dummy.cpp
g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I. -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I../../include -I../../include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I../../include/QtScxml/5.15.1 -I../../include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -o .obj/qscxmlexecutablecontent.o /usr/src/qt-everywhere-src-5.15.1/qtscxml/src/scxml/qscxmlexecutablecontent.cpp
g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I. -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I../../include -I../../include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I../../include/QtScxml/5.15.1 -I../../include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -o .obj/qscxmlerror.o /usr/src/qt-everywhere-src-5.15.1/qtscxml/src/scxml/qscxmlerror.cpp
g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I. -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I../../include -I../../include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I../../include/QtScxml/5.15.1 -I../../include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -o .obj/qscxmltabledata.o /usr/src/qt-everywhere-src-5.15.1/qtscxml/src/scxml/qscxmltabledata.cpp
g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I. -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I../../include -I../../include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I../../include/QtScxml/5.15.1 -I../../include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -o .obj/main.o /usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc/main.cpp
/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/bin/rcc -name templates /usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc/templates.qrc -o .rcc/qrc_templates.cpp
/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/bin/moc -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB --include /usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/tools/qscxmlc/.moc/moc_predefs.h -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include /usr/src/qt-everywhere-src-5.15.1/qtscxml/src/scxml/qscxmlerror.h -o .moc/moc_qscxmlerror.cpp
/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/bin/moc -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB --include /usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/tools/qscxmlc/.moc/moc_predefs.h -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I. -I/usr/include/c++/10.2.0 -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/10.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed -I/usr/include /usr/src/qt-everywhere-src-5.15.1/qtscxml/src/scxml/qscxmlcompiler.cpp -o .moc/qscxmlcompiler.moc
/usr/src/qt-everywhere-src-5.15.1/qtscxml/src/scxml/qscxmlerror.h:0: Note: No relevant classes found. No output generated.
g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I. -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I../../include -I../../include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I../../include/QtScxml/5.15.1 -I../../include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -o .obj/qrc_templates.o .rcc/qrc_templates.cpp
g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I. -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I../../include -I../../include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I../../include/QtScxml/5.15.1 -I../../include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -o .obj/moc_qscxmlerror.o .moc/moc_qscxmlerror.cpp
/usr/src/qt-everywhere-src-5.15.1/qtscxml/src/scxml/qscxmlcompiler.cpp:0: Note: No relevant classes found. No output generated.
g++ -c -pipe -O2 -std=c++1z -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DBUILD_QSCXMLC -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/tools/qscxmlc -I. -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml -I../../include -I../../include/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtscxml/include/QtScxml/5.15.1/QtScxml -I../../include/QtScxml/5.15.1 -I../../include/QtScxml/5.15.1/QtScxml -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1 -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore/5.15.1/QtCore -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.1/qtbase/mkspecs/linux-g++ -o .obj/qscxmlcompiler.o /usr/src/qt-everywhere-src-5.15.1/qtscxml/src/scxml/qscxmlcompiler.cpp
g++ -Wl,-O1 -Wl,--enable-new-dtags -o ../../bin/qscxmlc .obj/generator.o .obj/qscxmlc.o .obj/scxmlcppdumper.o .obj/qscxmlcompiler.o .obj/qscxmlexecutablecontent.o .obj/qscxmlerror.o .obj/qscxmltabledata.o .obj/main.o .obj/qrc_templates.o .obj/moc_qscxmlerror.o   /usr/src/qt-everywhere-src-5.15.1/build-qt/qtbase/lib/libQt5Core.so -lpthread   
make[3]: Leaving directory '/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/tools/qscxmlc'
make[2]: Leaving directory '/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml/tools'
make[1]: Leaving directory '/usr/src/qt-everywhere-src-5.15.1/build-qt/qtscxml'

++ Mark Compile stop   : "qt5" "5.15.1" "Tue, 06 Oct 2020 15:06:08 +0000"
[qt5-5.15.zip](https://github.com/lunar-linux/moonbase-kde/files/5345681/qt5-5.15.zip)
`

**Comment by stumbles** [comment]
Obviously XML related. Have you tried lunar fix and/or recompile any XML related modules?

**Comment by florin65** [comment]
qt5 was bumped to 5.15.2 version.
Please try it out.
