### ISSUE TITLE
Qt5:still can not complie

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#210]
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -c -pipe -O2 -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WAYLANDCOMPOSITOR_LIB -DQT_QUICK_LIB -DQT_XKBCOMMON_SUPPORT_LIB -DQT_EGL_SUPPORT_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/src/plugins/hardwareintegration/compositor/wayland-eglstream-controller -I. -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/src/hardwareintegration/compositor/wayland-eglstream-controller -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandCompositor/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandCompositor/5.15.2/QtWaylandCompositor -I../../../../../include/QtWaylandCompositor/5.15.2 -I../../../../../include/QtWaylandCompositor/5.15.2/QtWaylandCompositor -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandCompositor -I../../../../../include -I../../../../../include/QtWaylandCompositor -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQuick/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQuick/5.15.2/QtQuick -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQuick/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQuick/5.15.2/QtQuick -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQuick -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQuick -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport/5.15.2/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtEglSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtEglSupport/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtEglSupport/5.15.2/QtEglSupport -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtEglSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui/5.15.2/QtGui -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui/5.15.2/QtGui -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQmlModels/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQmlModels/5.15.2/QtQmlModels -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQmlModels/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQmlModels/5.15.2/QtQmlModels -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQmlModels -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQmlModels -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQml/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQml/5.15.2/QtQml -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQml/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQml/5.15.2/QtQml -I/usr/src/qt-everywhere-src-5.15.2/qtdeclarative/include/QtQml -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/include/QtQml -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtNetwork -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtNetwork -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore/5.15.2/QtCore -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore/5.15.2/QtCore -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.2/qtbase/mkspecs/linux-g++ -o .obj/qwayland-server-wl-eglstream-controller.o qwayland-server-wl-eglstream-controller.cpp
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -c -pipe -O2 -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SERVICE_SUPPORT_LIB -DQT_XKBCOMMON_SUPPORT_LIB -DQT_GLX_SUPPORT_LIB -DQT_WAYLANDCLIENT_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/src/plugins/hardwareintegration/client/xcomposite-glx -I. -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/src/hardwareintegration/client/xcomposite-glx -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/src/hardwareintegration/client/xcomposite_share -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandClient/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandClient/5.15.2/QtWaylandClient -I../../../../../include/QtWaylandClient/5.15.2 -I../../../../../include/QtWaylandClient/5.15.2/QtWaylandClient -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtServiceSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtServiceSupport/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtServiceSupport/5.15.2/QtServiceSupport -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtServiceSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport/5.15.2/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGlxSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGlxSupport/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGlxSupport/5.15.2/QtGlxSupport -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGlxSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui/5.15.2/QtGui -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui/5.15.2/QtGui -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandClient -I../../../../../include -I../../../../../include/QtWaylandClient -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore/5.15.2/QtCore -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore/5.15.2/QtCore -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtDBus -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtDBus -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.2/qtbase/mkspecs/linux-g++ -o .obj/main.o /usr/src/qt-everywhere-src-5.15.2/qtwayland/src/plugins/hardwareintegration/client/xcomposite-glx/main.cpp
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -c -pipe -O2 -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_LINKED_LIST -DQT_DEPRECATED_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SERVICE_SUPPORT_LIB -DQT_XKBCOMMON_SUPPORT_LIB -DQT_GLX_SUPPORT_LIB -DQT_WAYLANDCLIENT_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/src/plugins/hardwareintegration/client/xcomposite-glx -I. -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/src/hardwareintegration/client/xcomposite-glx -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/src/hardwareintegration/client/xcomposite_share -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandClient/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandClient/5.15.2/QtWaylandClient -I../../../../../include/QtWaylandClient/5.15.2 -I../../../../../include/QtWaylandClient/5.15.2/QtWaylandClient -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtServiceSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtServiceSupport/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtServiceSupport/5.15.2/QtServiceSupport -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtServiceSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtXkbCommonSupport/5.15.2/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtXkbCommonSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGlxSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGlxSupport/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGlxSupport/5.15.2/QtGlxSupport -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGlxSupport -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui/5.15.2/QtGui -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui/5.15.2/QtGui -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include -I/usr/src/qt-everywhere-src-5.15.2/qtwayland/include/QtWaylandClient -I../../../../../include -I../../../../../include/QtWaylandClient -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtGui -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtGui -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore/5.15.2/QtCore -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore/5.15.2 -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore/5.15.2/QtCore -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtDBus -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtDBus -I/usr/src/qt-everywhere-src-5.15.2/qtbase/include/QtCore -I/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/include/QtCore -I.moc -I/usr/src/qt-everywhere-src-5.15.2/qtbase/mkspecs/linux-g++ -o .obj/qwayland-xcomposite.o qwayland-xcomposite.cpp
rm -f libqt-wayland-compositor-wayland-eglstream-controller.so
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -Wl,--no-undefined -Wl,-O1 -Wl,--enable-new-dtags -shared -o libqt-wayland-compositor-wayland-eglstream-controller.so .obj/main.o .obj/waylandeglstreamintegration.o .obj/waylandeglstreamcontroller.o .obj/wayland-wl-eglstream-controller-protocol.o .obj/qwayland-server-wl-eglstream-controller.o  /usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/lib/libQt5WaylandCompositor.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/lib/libQt5Quick.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5XkbCommonSupport.a /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5EglSupport.a -lEGL -lXext -lX11 -lm /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Gui.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/lib/libQt5QmlModels.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtdeclarative/lib/libQt5Qml.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Network.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Core.so -lGL -lpthread -lwayland-server -lxkbcommon -ldl -lEGL -lwayland-server -lwayland-egl -lwayland-client   
rm -f libshm-emulation-server.so
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -Wl,--no-undefined -Wl,-O1 -Wl,--enable-new-dtags -Wl,-rpath-link,/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib -shared -o libshm-emulation-server.so .obj/shmserverbufferintegration.o .obj/main.o .obj/wayland-shm-emulation-server-buffer-protocol.o .obj/qwayland-shm-emulation-server-buffer.o  /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5ServiceSupport.a /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5XkbCommonSupport.a /usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/lib/libQt5WaylandClient.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Gui.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5DBus.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Core.so -lGL -lpthread -lwayland-cursor -lwayland-client -lxkbcommon    
rm -f libdrm-egl-server.so
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -Wl,--no-undefined -Wl,-O1 -Wl,--enable-new-dtags -Wl,-rpath-link,/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib -shared -o libdrm-egl-server.so .obj/drmeglserverbufferintegration.o .obj/main.o .obj/wayland-drm-egl-server-buffer-protocol.o .obj/qwayland-drm-egl-server-buffer.o  /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5ServiceSupport.a /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5XkbCommonSupport.a /usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/lib/libQt5WaylandClient.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Gui.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5DBus.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Core.so -lGL -lpthread -lEGL -lwayland-cursor -lwayland-client -lxkbcommon    
mv -f libqt-wayland-compositor-wayland-eglstream-controller.so ../../../../../plugins/wayland-graphics-integration-server/libqt-wayland-compositor-wayland-eglstream-controller.so
make[6]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src/plugins/hardwareintegration/compositor/wayland-eglstream-controller'
make[5]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src/plugins/hardwareintegration/compositor'
mv -f libshm-emulation-server.so ../../../../../plugins/wayland-graphics-integration-client/libshm-emulation-server.so
make[6]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src/plugins/hardwareintegration/client/shm-emulation-server'
mv -f libdrm-egl-server.so ../../../../../plugins/wayland-graphics-integration-client/libdrm-egl-server.so
make[6]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src/plugins/hardwareintegration/client/drm-egl-server'
rm -f libxcomposite-glx.so
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -Wl,--no-undefined -Wl,-O1 -Wl,--enable-new-dtags -Wl,-rpath-link,/usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib -shared -o libxcomposite-glx.so .obj/qwaylandxcompositebuffer.o .obj/qwaylandxcompositeglxcontext.o .obj/qwaylandxcompositeglxintegration.o .obj/qwaylandxcompositeglxwindow.o .obj/main.o .obj/wayland-xcomposite-protocol.o .obj/qwayland-xcomposite.o  /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5ServiceSupport.a /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5XkbCommonSupport.a /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5GlxSupport.a /usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/lib/libQt5WaylandClient.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Gui.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5DBus.so /usr/src/qt-everywhere-src-5.15.2/build-qt/qtbase/lib/libQt5Core.so -lpthread -lXcomposite -lwayland-cursor -lwayland-client -lGL -ldl -lxkbcommon -lXext -lX11 -lm    
mv -f libxcomposite-glx.so ../../../../../plugins/wayland-graphics-integration-client/libxcomposite-glx.so
make[6]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src/plugins/hardwareintegration/client/xcomposite-glx'
make[5]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src/plugins/hardwareintegration/client'
make[4]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src/plugins/hardwareintegration'
make[3]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src/plugins'
make[2]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland/src'
make[1]: Leaving directory '/usr/src/qt-everywhere-src-5.15.2/build-qt/qtwayland'

complie stop here again and again.

[qt5-5.15.zip](https://github.com/lunar-linux/moonbase-kde/files/5729812/qt5-5.15.zip)

**Comment by lhw828** [comment]
Project ERROR: Library 'assimp' is not defined.

**Comment by lhw828** [comment]
Checking dependencies for assimp 
Building assimp version 5.0.1
cmake: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory
Creating /var/log/lunar/compile/assimp-5.0.1.xz

**Comment by florin65** [comment]
do a 'lin icu4c' first

**Comment by lhw828** [comment]
https://github.com/lunar-linux/moonbase-kde/commit/53c6404367f376e8624a9e7040e8b5be0046cc49

Finally, the patch fixed Qt5, a few months later.
