### ISSUE TITLE
kalarm:libqgpgme.so.7 not found

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#237]
[ 89%] Building CXX object src/CMakeFiles/kalarm_bin.dir/commandoptions.cpp.o
[ 90%] Building CXX object src/CMakeFiles/kalarm_bin.dir/resourceselector.cpp.o
[ 91%] Building CXX object src/CMakeFiles/kalarm_bin.dir/datepicker.cpp.o
[ 91%] Building CXX object src/CMakeFiles/kalarm_bin.dir/daymatrix.cpp.o
[ 92%] Building CXX object src/CMakeFiles/kalarm_bin.dir/templatepickdlg.cpp.o
[ 92%] Building CXX object src/CMakeFiles/kalarm_bin.dir/templatedlg.cpp.o
[ 93%] Building CXX object src/CMakeFiles/kalarm_bin.dir/templatemenuaction.cpp.o
[ 94%] Building CXX object src/CMakeFiles/kalarm_bin.dir/wakedlg.cpp.o
[ 94%] Building CXX object src/CMakeFiles/kalarm_bin.dir/migratekde4files.cpp.o
[ 95%] Building CXX object src/CMakeFiles/kalarm_bin.dir/akonadicollectionsearch.cpp.o
[ 96%] Building CXX object src/CMakeFiles/kalarm_bin.dir/kalarmadaptor.cpp.o
[ 96%] Building CXX object src/CMakeFiles/kalarm_bin.dir/kmailinterface.cpp.o
[ 97%] Building CXX object src/CMakeFiles/kalarm_bin.dir/notifications_interface.cpp.o
[ 98%] Building CXX object src/CMakeFiles/kalarm_bin.dir/dbusproperties.cpp.o
[ 98%] Building CXX object src/CMakeFiles/kalarm_bin.dir/kalarmsettings.cpp.o
[ 99%] Building CXX object src/CMakeFiles/kalarm_bin.dir/kalarmconfig.cpp.o
[ 99%] Building CXX object src/CMakeFiles/kalarm_bin.dir/kalarmdirsettings.cpp.o
[100%] Linking CXX executable ../bin/kalarm
/usr/bin/ld: warning: libqgpgme.so.7, needed by /usr/lib64/libKF5AkonadiContact.so.5.19.3, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::CryptoConfigEntry::stringValueList() const'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::done()'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::~Job()'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `operator<<(QDebug, GpgME::Error const&)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::KeyGenerationJob::result(GpgME::KeyGenerationResult const&, QByteArray const&, QString const&, GpgME::Error const&)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::progress(QString const&, int, int)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `typeinfo for QGpgME::Job'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::qt_metacast(char const*)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::DefaultKeyGenerationJob::DefaultKeyGenerationJob(QObject*)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::DefaultKeyGenerationJob::staticMetaObject'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::qt_metacall(QMetaObject::Call, int, void**)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::ListAllKeysJob::staticMetaObject'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::KeyGenerationJob::staticMetaObject'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::KeyListJob::result(GpgME::KeyListResult const&, std::vector<GpgME::Key, std::allocator<GpgME::Key> > const&, QString const&, GpgME::Error const&)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::CryptoConfig::entry(QString const&, QString const&) const'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::staticMetaObject'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::smime()'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::Job(QObject*)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::DefaultKeyGenerationJob::result(GpgME::KeyGenerationResult const&, QByteArray const&, QString const&, GpgME::Error const&)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::QByteArrayDataProvider::QByteArrayDataProvider(QByteArray const&)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::openpgp()'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::context(QGpgME::Job*)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::Job::isAuditLogSupported() const'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::KeyListJob::staticMetaObject'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::KeyListJob::nextKey(GpgME::Key const&)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::DefaultKeyGenerationJob::start(QString const&, QString const&)'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::cryptoConfig()'
/usr/bin/ld: /usr/lib/libKF5Libkleo.so.5: undefined reference to `QGpgME::QByteArrayDataProvider::~QByteArrayDataProvider()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/kalarm_bin.dir/build.make:1955: bin/kalarm] Error 1
make[1]: *** [CMakeFiles/Makefile2:648: src/CMakeFiles/kalarm_bin.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

This problem cannot be resolved when i run `lin -rc gpgme` .

**Comment by stumbles** [comment]
Do at least a lunar fix on libkleo and akonadi-contacts. SOname versions change on a gpgme bump. Might wanna do a lunar fix to catch other modules using gpgme.
