### ISSUE TITLE
kxmlgui:expected type-specifier before 'QSslSocket'

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#239]
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/kxmlgui-5.95.0/kxmlgui-oosb
[  1%] Generating mo...
[  3%] Generating ts...
[  4%] Automatic MOC for target KF5XmlGui
[  6%] Automatic MOC for target ksendbugmail
[  6%] Built target tsfiles-677903b7675a96cb15dbc20552446dfb
[  6%] Built target ksendbugmail_autogen
[  8%] Building CXX object src/ksendbugmail/CMakeFiles/ksendbugmail.dir/ksendbugmail_autogen/mocs_compilation.cpp.o
[  9%] Building CXX object src/ksendbugmail/CMakeFiles/ksendbugmail.dir/smtp.cpp.o
[ 11%] Building CXX object src/ksendbugmail/CMakeFiles/ksendbugmail.dir/main.cpp.o
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
[ 11%] Built target pofiles-677903b7675a96cb15dbc20552446dfb
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
/usr/src/kxmlgui-5.95.0/src/ksendbugmail/smtp.cpp: In member function 'void SMTP::connectTimerTick()':
/usr/src/kxmlgui-5.95.0/src/ksendbugmail/smtp.cpp:162:16: error: expected type-specifier before 'QSslSocket'
  162 |     sock = new QSslSocket(this);
      |                ^~~~~~~~~~
make[2]: *** [src/ksendbugmail/CMakeFiles/ksendbugmail.dir/build.make:104: src/ksendbugmail/CMakeFiles/ksendbugmail.dir/smtp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:352: src/ksendbugmail/CMakeFiles/ksendbugmail.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 11%] Built target KF5XmlGui_autogen
make: *** [Makefile:136: all] Error 2

**Comment by stumbles** [comment]
lunar fix your box.
