### ISSUE TITLE
qtwebengine:make: *** [Makefile:49: sub-src-make_first] Error 2

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#240]
.15.5/include -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/3rdparty/chromium -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5 -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5/QtPdf -I../../../include/QtPdf/5.15.5 -I../../../include/QtPdf/5.15.5/QtPdf -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf -I../../../include -I../../../include/QtPdf -I/usr/include/qt5/QtQuick/5.15.5 -I/usr/include/qt5/QtQuick/5.15.5/QtQuick -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui/5.15.5 -I/usr/include/qt5/QtGui/5.15.5/QtGui -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQmlModels/5.15.5 -I/usr/include/qt5/QtQmlModels/5.15.5/QtQmlModels -I/usr/include/qt5/QtQml/5.15.5 -I/usr/include/qt5/QtQml/5.15.5/QtQml -I/usr/include/qt5/QtCore/5.15.5 -I/usr/include/qt5/QtCore/5.15.5/QtCore -I/usr/include/qt5/QtQmlModels -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I.moc -I/usr/lib/qt5/mkspecs/linux-g++ -o .obj/moc_qquickpdfnavigationstack_p.o .moc/moc_qquickpdfnavigationstack_p.cpp
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -c -pipe -fPIC -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PDF_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/pdf/quick -I. -I/usr/src/qtwebengine-everywhere-src-5.15.5/include -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/3rdparty/chromium -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5 -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5/QtPdf -I../../../include/QtPdf/5.15.5 -I../../../include/QtPdf/5.15.5/QtPdf -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf -I../../../include -I../../../include/QtPdf -I/usr/include/qt5/QtQuick/5.15.5 -I/usr/include/qt5/QtQuick/5.15.5/QtQuick -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui/5.15.5 -I/usr/include/qt5/QtGui/5.15.5/QtGui -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQmlModels/5.15.5 -I/usr/include/qt5/QtQmlModels/5.15.5/QtQmlModels -I/usr/include/qt5/QtQml/5.15.5 -I/usr/include/qt5/QtQml/5.15.5/QtQml -I/usr/include/qt5/QtCore/5.15.5 -I/usr/include/qt5/QtCore/5.15.5/QtCore -I/usr/include/qt5/QtQmlModels -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I.moc -I/usr/lib/qt5/mkspecs/linux-g++ -o .obj/moc_qquickpdfselection_p.o .moc/moc_qquickpdfselection_p.cpp
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -c -pipe -fPIC -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PDF_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/pdf/quick -I. -I/usr/src/qtwebengine-everywhere-src-5.15.5/include -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/3rdparty/chromium -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5 -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5/QtPdf -I../../../include/QtPdf/5.15.5 -I../../../include/QtPdf/5.15.5/QtPdf -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf -I../../../include -I../../../include/QtPdf -I/usr/include/qt5/QtQuick/5.15.5 -I/usr/include/qt5/QtQuick/5.15.5/QtQuick -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui/5.15.5 -I/usr/include/qt5/QtGui/5.15.5/QtGui -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQmlModels/5.15.5 -I/usr/include/qt5/QtQmlModels/5.15.5/QtQmlModels -I/usr/include/qt5/QtQml/5.15.5 -I/usr/include/qt5/QtQml/5.15.5/QtQml -I/usr/include/qt5/QtCore/5.15.5 -I/usr/include/qt5/QtCore/5.15.5/QtCore -I/usr/include/qt5/QtQmlModels -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I.moc -I/usr/lib/qt5/mkspecs/linux-g++ -o .obj/moc_qquickpdflinkmodel_p.o .moc/moc_qquickpdflinkmodel_p.cpp
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -c -pipe -fPIC -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PDF_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/pdf/quick -I. -I/usr/src/qtwebengine-everywhere-src-5.15.5/include -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/3rdparty/chromium -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5 -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5/QtPdf -I../../../include/QtPdf/5.15.5 -I../../../include/QtPdf/5.15.5/QtPdf -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf -I../../../include -I../../../include/QtPdf -I/usr/include/qt5/QtQuick/5.15.5 -I/usr/include/qt5/QtQuick/5.15.5/QtQuick -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui/5.15.5 -I/usr/include/qt5/QtGui/5.15.5/QtGui -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQmlModels/5.15.5 -I/usr/include/qt5/QtQmlModels/5.15.5/QtQmlModels -I/usr/include/qt5/QtQml/5.15.5 -I/usr/include/qt5/QtQml/5.15.5/QtQml -I/usr/include/qt5/QtCore/5.15.5 -I/usr/include/qt5/QtCore/5.15.5/QtCore -I/usr/include/qt5/QtQmlModels -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I.moc -I/usr/lib/qt5/mkspecs/linux-g++ -o .obj/moc_qquickpdfsearchmodel_p.o .moc/moc_qquickpdfsearchmodel_p.cpp
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -c -pipe -fPIC -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PDF_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/pdf/quick -I. -I/usr/src/qtwebengine-everywhere-src-5.15.5/include -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/3rdparty/chromium -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5 -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5/QtPdf -I../../../include/QtPdf/5.15.5 -I../../../include/QtPdf/5.15.5/QtPdf -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf -I../../../include -I../../../include/QtPdf -I/usr/include/qt5/QtQuick/5.15.5 -I/usr/include/qt5/QtQuick/5.15.5/QtQuick -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui/5.15.5 -I/usr/include/qt5/QtGui/5.15.5/QtGui -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQmlModels/5.15.5 -I/usr/include/qt5/QtQmlModels/5.15.5/QtQmlModels -I/usr/include/qt5/QtQml/5.15.5 -I/usr/include/qt5/QtQml/5.15.5/QtQml -I/usr/include/qt5/QtCore/5.15.5 -I/usr/include/qt5/QtCore/5.15.5/QtCore -I/usr/include/qt5/QtQmlModels -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I.moc -I/usr/lib/qt5/mkspecs/linux-g++ -o .obj/plugin.o /usr/src/qtwebengine-everywhere-src-5.15.5/src/pdf/quick/plugin.cpp
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -c -pipe -fPIC -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -D_REENTRANT -fPIC -DQT_NO_LINKED_LIST -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_PDF_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/pdf/quick -I. -I/usr/src/qtwebengine-everywhere-src-5.15.5/include -I/usr/src/qtwebengine-everywhere-src-5.15.5/src/3rdparty/chromium -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5 -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf/5.15.5/QtPdf -I../../../include/QtPdf/5.15.5 -I../../../include/QtPdf/5.15.5/QtPdf -I/usr/src/qtwebengine-everywhere-src-5.15.5/include/QtPdf -I../../../include -I../../../include/QtPdf -I/usr/include/qt5/QtQuick/5.15.5 -I/usr/include/qt5/QtQuick/5.15.5/QtQuick -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui/5.15.5 -I/usr/include/qt5/QtGui/5.15.5/QtGui -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQmlModels/5.15.5 -I/usr/include/qt5/QtQmlModels/5.15.5/QtQmlModels -I/usr/include/qt5/QtQml/5.15.5 -I/usr/include/qt5/QtQml/5.15.5/QtQml -I/usr/include/qt5/QtCore/5.15.5 -I/usr/include/qt5/QtCore/5.15.5/QtCore -I/usr/include/qt5/QtQmlModels -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I.moc -I/usr/lib/qt5/mkspecs/linux-g++ -o .obj/moc_qquicktableviewextra_p.o .moc/moc_qquicktableviewextra_p.cpp
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
rm -f libpdfplugin.so
CCACHE_SLOPPINESS="pch_defines,time_macros${CCACHE_SLOPPINESS+,$CCACHE_SLOPPINESS}" CCACHE_CPP2=true ccache g++ -Wl,--enable-new-dtags -shared -o libpdfplugin.so .obj/plugin.o .obj/qquickpdfdocument.o .obj/qquickpdflinkmodel.o .obj/qquickpdfnavigationstack.o .obj/qquickpdfsearchmodel.o .obj/qquickpdfselection.o .obj/qquicktableviewextra.o .obj/qrc_resources.o .obj/moc_qquickpdfdocument_p.o .obj/moc_qquickpdflinkmodel_p.o .obj/moc_qquickpdfnavigationstack_p.o .obj/moc_qquickpdfsearchmodel_p.o .obj/moc_qquickpdfselection_p.o .obj/moc_qquicktableviewextra_p.o  /usr/src/qtwebengine-everywhere-src-5.15.5/build/lib/libQt5Pdf.so /usr/lib/qt5/libQt5Quick.so /usr/lib/qt5/libQt5Gui.so /usr/lib/qt5/libQt5QmlModels.so /usr/lib/qt5/libQt5Qml.so /usr/lib/qt5/libQt5Network.so /usr/lib/qt5/libQt5Core.so -lGL -pthread    
/usr/bin/ld: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
/usr/bin/ld: /lib/libz.so.1: no version information available (required by /usr/lib/libctf.so.0)
mv -f libpdfplugin.so ../../../qml/QtQuick/Pdf/libpdfplugin.so
make[3]: Leaving directory '/usr/src/qtwebengine-everywhere-src-5.15.5/build/src/pdf/quick'
make[2]: Leaving directory '/usr/src/qtwebengine-everywhere-src-5.15.5/build/src/pdf'
make[1]: Leaving directory '/usr/src/qtwebengine-everywhere-src-5.15.5/build/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
Creating /var/log/lunar/compile/qtwebengine-5.15.5.xz

**Comment by stumbles** [comment]
Again, lunar fix your box. libz so version changed.
