### ISSUE TITLE
libkgeomap:The following imported targets are referenced, but are missing: Astro

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#246]
Building libkgeomap version 20.08.3
-- The C compiler identification is GNU 12.1.1
-- The CXX compiler identification is GNU 12.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /var/lib/lunar/compilers/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ----------------------------------------------------------------------------------
-- Starting CMake configuration for: libkgeomap
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Found KF5I18n: /usr/lib64/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.98.0") 
-- Found KF5Config: /usr/lib64/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.98.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found KF5KIO: /usr/lib64/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.98.0") 
-- Found KF5: success (found suitable version "5.98.0", minimum required is "5.18.0") found components: I18n Config KIO 
CMake Error at CMakeLists.txt:77 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/Marble/MarbleConfig.cmake

  but it set Marble_FOUND to FALSE so package "Marble" is considered to be
  NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: Astro

-- Configuring incomplete, errors occurred!
See also "/usr/src/libkgeomap-20.08.3/libkgeomap-oosb/CMakeFiles/CMakeOutput.log".
Creating /var/log/lunar/compile/libkgeomap-20.08.3.xz

**Comment by stumbles** [comment]
Astro is provided by marble by default so I'd suggest relin marble. If libkgeomap still tanks after that then you got bigger problems.

**Comment by stumbles** [comment]
Its been three months. Assuming this resolved itself and closing.
