### ISSUE TITLE
qtwebengine:collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#249]
/usr/src/qtwebengine-5.15.12/build/src/core/release/obj/base/third_party/xdg_user_dirs/libxdg_user_dirs.a /usr/src/qtwebengine-5.15.12/build/src/core/release/obj/third_party/ced/libced.a -Wl,--end-group -ldl -lpthread -lrt -licui18n -licuuc -licudata -levent  
/usr/bin/ld: warning: libicui18n.so.71, needed by /usr/lib/qt5/libQt5Core.so, may conflict with libicui18n.so.72
/usr/bin/ld: warning: libicuuc.so.71, needed by /usr/lib/qt5/libQt5Core.so, may conflict with libicuuc.so.72
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:313: ../../../bin/qwebengine_convert_dict] Error 1
make[2]: Leaving directory '/usr/src/qtwebengine-5.15.12/build/src/tools/qwebengine_convert_dict'
make[1]: *** [Makefile:130: sub-tools-qwebengine_convert_dict-make_first] Error 2
make[1]: Leaving directory '/usr/src/qtwebengine-5.15.12/build/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
++ Mark Compile stop   : "qtwebengine" "5.15.12" "Mon, 06 Mar 2023 13:08:20 +0000"

[qtwebengine-5.15.zip](https://github.com/lunar-linux/moonbase-kde/files/10918294/qtwebengine-5.15.zip)

**Comment by stumbles** [comment]
Recompile any dependency that involves icu4c to include qt5.

**Comment by stumbles** [comment]
Two months gone by, closing
