### ISSUE TITLE
kcolorpicker:not providing "FindQt5.cmake" in CMAKE_MODULE_PATH 

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-kde#276]
Checking dependencies for kcolorpicker 
Building kcolorpicker version 0.3.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:26 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.9.4) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
Creating /var/log/lunar/compile/kcolorpicker-0.3.0.xz 
! Problem detected during BUILD
bash-5.1# qmake-qt5 -v
QMake version 3.1
Using Qt version 5.15.11 in /usr/lib/qt5
bash-5.1# 

In fact, my Qt5 is in normal working condition.

**Comment by stumbles** [comment]
Closing with commit 21b556adb0839c90ce043a7911ba2c3e3c12810c which bumps this module to 0.3.1 and moved to depends on qt6.
